-- CreateTable
CREATE TABLE "Candidate" (
    "id" SERIAL NOT NULL,
    "name" TEXT NOT NULL,
    "contactNumber" TEXT NOT NULL,
    "alternateContactNumber" TEXT,
    "email" TEXT NOT NULL,
    "sourcedFrom" TEXT,
    "employmentType" TEXT,
    "domainExperience" TEXT,
    "company" TEXT,
    "role" TEXT,
    "currentCTC" DOUBLE PRECISION,
    "expectedCTC" DOUBLE PRECISION,
    "workingStatus" TEXT,
    "noticePeriod" INTEGER,
    "location" TEXT,
    "relocate" BOOLEAN,
    "preferredLocation" TEXT,
    "interviewAvailability" TEXT,
    "clientName" TEXT,
    "demandCode" TEXT,
    "interviewTakenBy" TEXT,
    "comments" TEXT[],
    "status" TEXT,
    "followUps" TEXT,
    "updatedBy" TEXT,
    "offersAny" BOOLEAN NOT NULL,
    "screeningComment" TEXT,
    "technicalSkills" TEXT NOT NULL,
    "relevantExperience" TEXT NOT NULL,
    "primarySkillExp" TEXT,
    "secondarySkillExp" TEXT,
    "nammaqaUpdate" TEXT,
    "clientInterviewStatus" TEXT,
    "feedback" TEXT,
    "resumeLink" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Candidate_pkey" PRIMARY KEY ("id")
);
